# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 5
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/it/Documents/rvsoc_v3/vivado_proj/vivado_proj.cache/wt [current_project]
set_property parent.project_path /home/it/Documents/rvsoc_v3/vivado_proj/vivado_proj.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty-a7-100:part0:1.1 [current_project]
set_property ip_output_repo /home/it/Documents/rvsoc_v3/vivado_proj/vivado_proj.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog /home/it/Documents/rvsoc_v3/src/soc/WishboneInterconnect/wb_intercon.svh
set_property file_type "Verilog Header" [get_files /home/it/Documents/rvsoc_v3/src/soc/WishboneInterconnect/wb_intercon.svh]
read_verilog -library xil_defaultlib -sv {
  /home/it/Documents/rvsoc_v3/src/soc/core/lib.sv
  /home/it/Documents/rvsoc_v3/src/soc/core/alignment_units.sv
  /home/it/Documents/rvsoc_v3/src/soc/core/alu.sv
  /home/it/Documents/rvsoc_v3/src/soc/core/alu_control.sv
  /home/it/Documents/rvsoc_v3/src/soc/uncore/gpio/bidirec.sv
  /home/it/Documents/rvsoc_v3/src/soc/core/branch_controller.sv
  /home/it/Documents/rvsoc_v3/src/soc/core/control_unit.sv
  /home/it/Documents/rvsoc_v3/src/soc/core/data_mem.sv
  /home/it/Documents/rvsoc_v3/src/soc/core/data_path.sv
  /home/it/Documents/rvsoc_v3/src/soc/core/forwarding_unit.sv
  /home/it/Documents/rvsoc_v3/src/soc/uncore/gpio/gpio_top.sv
  /home/it/Documents/rvsoc_v3/src/soc/core/hazard_controller.sv
  /home/it/Documents/rvsoc_v3/src/soc/core/imm_gen.sv
  /home/it/Documents/rvsoc_v3/src/soc/core/main_control.sv
  /home/it/Documents/rvsoc_v3/src/soc/core/pipeline_controller.sv
  /home/it/Documents/rvsoc_v3/src/soc/core/program_counter.sv
  /home/it/Documents/rvsoc_v3/src/soc/core/reg_file.sv
  /home/it/Documents/rvsoc_v3/src/soc/core/rom.sv
  /home/it/Documents/rvsoc_v3/src/soc/rv32i_soc.sv
  /home/it/Documents/rvsoc_v3/src/soc/core/rv32i_top.sv
  /home/it/Documents/rvsoc_v3/src/soc/WishboneInterconnect/wb_intercon.sv
  /home/it/Documents/rvsoc_v3/src/soc/WishboneInterconnect/wishbone_controller.sv
  /home/it/Documents/rvsoc_v3/src/soc/rv32i_soc_fpga_top.sv
  /home/it/Documents/rvsoc_v3/src/soc/core/inst_mem.sv
}
read_verilog -library xil_defaultlib {
  /home/it/Documents/rvsoc_v3/src/soc/uncore/spi/fifo4.v
  /home/it/Documents/rvsoc_v3/src/soc/uncore/uart/raminfr.v
  /home/it/Documents/rvsoc_v3/src/soc/uncore/spi/simple_spi_top.v
  /home/it/Documents/rvsoc_v3/src/soc/uncore/uart/uart_defines.v
  /home/it/Documents/rvsoc_v3/src/soc/uncore/uart/uart_receiver.v
  /home/it/Documents/rvsoc_v3/src/soc/uncore/uart/uart_regs.v
  /home/it/Documents/rvsoc_v3/src/soc/uncore/uart/uart_rfifo.v
  /home/it/Documents/rvsoc_v3/src/soc/uncore/uart/uart_sync_flops.v
  /home/it/Documents/rvsoc_v3/src/soc/uncore/uart/uart_tfifo.v
  /home/it/Documents/rvsoc_v3/src/soc/uncore/uart/uart_top.v
  /home/it/Documents/rvsoc_v3/src/soc/uncore/uart/uart_transmitter.v
  /home/it/Documents/rvsoc_v3/src/soc/uncore/uart/uart_wb.v
  /home/it/Documents/rvsoc_v3/src/soc/WishboneInterconnect/wb_intercon_1.2.2-r1/wb_mux.v
  /home/it/Documents/rvsoc_v3/src/soc/uncore/gpio/gpio_defines.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/it/Documents/rvsoc_v3/src/soc/pin-assignment.xdc
set_property used_in_implementation false [get_files /home/it/Documents/rvsoc_v3/src/soc/pin-assignment.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top rv32i_soc_fpag_top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef rv32i_soc_fpag_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file rv32i_soc_fpag_top_utilization_synth.rpt -pb rv32i_soc_fpag_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
